Merge de la dev vers Master pour la v0.3
Edu-Focus/EduBot pull request #15
Opened 2020-02-05 21:48 UTC by MaitreRouge

Tout est dans le titre

2020-02-07 17:50 UTC, GribouilleVert requested changes

2020-02-07 17:50 UTC, GribouilleVert commented on functions/datefr.js
> +    var mois = new Array("Janvier", "Fevrier", "Mars", "Avril", "Mai", "Juin", "Juillet", "Aout", "Septembre", "Octobre", "Novembre", "Decembre");
C'est qwa cette syntaxe array php like horrible, un `[]` svp.

2020-02-07 19:45 UTC, MaitreRouge commented on functions/datefr.js
> +    var mois = new Array("Janvier", "Fevrier", "Mars", "Avril", "Mai", "Juin", "Juillet", "Aout", "Septembre", "Octobre", "Novembre", "Decembre");
...

2020-02-07 19:46 UTC, MaitreRouge commented on functions/datefr.js
> +    var mois = new Array("Janvier", "Fevrier", "Mars", "Avril", "Mai", "Juin", "Juillet", "Aout", "Septembre", "Octobre", "Novembre", "Decembre");
Je ferai mes embed aussi tant qu'on y est

2020-02-08 01:32 UTC, GribouilleVert approved these changes

2020-02-08 01:32 UTC, merged